src/QuizApp.FrontEnd/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using QuizApp.Data.Dal;
using QuizApp.Data.Entities.Models;
using Simple.OData.Client;

namespace QuizApp.FrontEnd.Controllers
{
    public class QuizController : Controller
    {
        private readonly DalContext _context;
		private readonly ODataClient _client;

        public QuizController(DalContext context, ODataClient client)
        {
            _context = context;
			_client = client;
		}

        //// GET: Quiz
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Quiz.ToListAsync());
        //}

		// GET: Quiz
		public IActionResult Index()
		{
			return View();
		}
		public async Task<ActionResult> Quiz_Read([DataSourceRequest] DataSourceRequest request)
		{

			var quizzes = await _client.For<Quiz>().FindEntriesAsync();
			return Json(quizzes.ToDataSourceResult(request)); //_context.Quiz.Select(s => new { s.Title, s.EventId, s.Active, s.PathToQuizReference }).ToDataSourceResultAsync(request));
		}

		[HttpPost]
		public async Task<ActionResult> Quiz_Create([DataSourceRequest] DataSourceRequest request, Quiz quiz)
		{

			Quiz returnQuiz = null; 
			if (quiz != null && ModelState.IsValid)
			{
				returnQuiz = await _client.For<Quiz>().Set(quiz).InsertEntryAsync(); //productService.Create(product);
			}

			return Json(new[] { returnQuiz }.ToDataSourceResult(request, ModelState));
			//throw new NotImplementedException();
		}

		[HttpPost]
		public async Task<ActionResult> Quiz_Update([DataSourceRequest] DataSourceRequest request, Quiz quiz)
		{
			Quiz updateQuiz = quiz;
			if (quiz != null && ModelState.IsValid)
			{
				updateQuiz = await _client.For<Quiz>().Key(updateQuiz.Id).Set(quiz).UpdateEntryAsync();
			}
			return Json(new[] { updateQuiz }.ToDataSourceResult(request, ModelState));
		}

		[HttpPost]
		public async Task<ActionResult> Quiz_Destroy([DataSourceRequest] DataSourceRequest request, Quiz quiz)
		{

			if (quiz != null)
			{
				await _client.For<Quiz>().Key(quiz.Id).DeleteEntryAsync();
			}

			return Json(new[] { string.Empty }.ToDataSourceResult(request, ModelState));
		}

		// GET: Quiz/Details/5
		public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quiz = await _context.Quiz
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quiz == null)
            {
                return NotFound();
            }

            return View(quiz);
        }

        // GET: Quiz/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Quiz/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,EventId,PathToQuizReference,Active,Id,Created,Modified")] Quiz quiz)
        {
            if (ModelState.IsValid)
            {
                _context.Add(quiz);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quiz);
        }

        // GET: Quiz/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quiz = await _context.Quiz.FindAsync(id);
            if (quiz == null)
            {
                return NotFound();
            }
            return View(quiz);
        }

        // POST: Quiz/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,Description,EventId,PathToQuizReference,Active,Id,Created,Modified")] Quiz quiz)
        {
            if (id != quiz.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quiz);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuizExists(quiz.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(quiz);
        }

        // GET: Quiz/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quiz = await _context.Quiz
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quiz == null)
            {
                return NotFound();
            }

            return View(quiz);
        }

        // POST: Quiz/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quiz = await _context.Quiz.FindAsync(id);
            _context.Quiz.Remove(quiz);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuizExists(int id)
        {
            return _context.Quiz.Any(e => e.Id == id);
        }

		internal class ODataResponse<T>
		{
			public List<T> Value { get; set; }
		}
	}
}

src/QuizApp.FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - QuizApp.FrontEnd</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.common-bootstrap.min.css" />
		<link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.bootstrap.min.css" />
		<link rel="stylesheet" href="~/css/site.css" />
		<link rel="stylesheet" href="~/css/custom.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet"
			  href="https://kendo.cdn.telerik.com/2017.2.621/styles/kendo.common-bootstrap.min.css"
			  asp-fallback-href="~/lib/kendo-ui/styles/kendo.common-nova.min.css"
			  asp-fallback-test-class="k-common-test-class"
			  asp-fallback-test-property="opacity" asp-fallback-test-value="0" />

		<link rel="stylesheet"
			  href="https://kendo.cdn.telerik.com/2017.2.621/styles/kendo.bootstrap.min.css"
			  asp-fallback-href="~/lib/kendo-ui/styles/kendo.nova.min.css"
			  asp-fallback-test-class="k-theme-test-class"
			  asp-fallback-test-property="opacity" asp-fallback-test-value="0" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/css/custom.min.css" asp-append-version="true" />
	</environment>
	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		@* Place Kendo UI scripts after jQuery *@
		<script src="~/lib/kendo-ui/js/kendo.all.min.js"></script>
		<script src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		@* Place Kendo UI scripts after jQuery *@
		<script src="https://kendo.cdn.telerik.com/2017.2.621/js/kendo.all.min.js"
				asp-fallback-src="~/lib/kendo-ui/js/kendo.all.min.js"
				asp-fallback-test="window.kendo">
		</script>
		<script src="https://kendo.cdn.telerik.com/2017.2.621/js/kendo.aspnetmvc.min.js"
				asp-fallback-src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"
				asp-fallback-test="kendo.data.transports['aspnetmvc-ajax']">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">QuizApp.FrontEnd</a>
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
					<li><a asp-area="" asp-controller="Quiz" asp-action="Index">Quizzes</a></li>
				</ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - QuizApp.FrontEnd</p>
        </footer>
    </div>

	

    @RenderSection("Scripts", required: false)
</body>
</html>